[package]
name = "clifford"
version = "0.1.0"
authors = ["Øystein Hovind <hovindo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[workspace]
members = [
    "pga3d",
]

[dev-dependencies]
pga3d = { path = "pga3d" }
quickcheck = "1.0.3"
